name: coffeecard
description: Cafe Analog Coffee card

publish_to: "none"

# Build pipeline will overwrite this
version: 0.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.2

dependencies:
  flutter:
    sdk: flutter

  # ui
  gap: 3.0.0
  shimmer: 3.0.0
  animations: 2.0.7
  dotted_border: 2.0.0+3
  flutter_layout_grid: 2.0.3
  cached_network_image: 3.2.3

  # Chopper api and rest client
  logger: 1.3.0
  chopper: 6.1.2

  # storage
  flutter_secure_storage: 8.0.0

  # dependency injection
  get_it: 7.6.0

  # State management
  flutter_bloc: 8.1.3
  bloc: 8.1.2
  stream_transform: 2.1.0

  # Utility
  meta: 1.9.1
  equatable: 2.0.5
  collection: 1.17.1

  # Internationalization and date formatting
  intl: 0.18.1

  # Url Launcher
  url_launcher: 6.1.11

  # crypto
  crypto: 3.0.3

  # rest
  http: 0.13.6

  # brightness
  screen_brightness: 0.2.2

  # firebase
  firebase_core: 2.13.0
  firebase_analytics: 10.4.1
  firebase_crashlytics: 3.3.1
  firebase_performance: 0.9.2+1

  # functional programming thingies
  fpdart: 0.6.0

  # Upgrade notifier
  upgrader: 7.0.1

  # env
  envied: 0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.4

  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.0

  # unit testing
  mockito: 5.4.1
  bloc_test: 9.1.2

  # Chopper api and rest client
  chopper_generator: 6.0.1
  json_serializable: 6.7.0
  swagger_dart_code_generator: 2.11.5

  # linter
  lint: 2.1.2
  dart_code_metrics: 5.7.4
  dart_code_metrics_presets: 1.8.0

  # env
  envied_generator: 0.3.0+3

# update splash screen:
# flutter pub run flutter_native_splash:create
# OR
# make splash
flutter_native_splash:
  color: "#362619"
  android_12:
    color: "#E5E2D7"

# update launcher icon:
# flutter pub run flutter_launcher_icons:main
# OR
# make icon
# WARNING! Don't run this command unless you are sure what you are doing.
# flutter_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/icon/Icon.png"
#   adaptive_icon_background: "assets/icon/Background.png"
#   adaptive_icon_foreground: "assets/icon/Foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/profile_icons/

  fonts:
    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/roboto_flex/RobotoFlex.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/roboto_mono/RobotoMono-Regular.ttf
        - asset: assets/fonts/roboto_mono/RobotoMono-Bold.ttf
          weight: 700
    - family: AnalogIcons
      fonts:
        - asset: assets/fonts/AnalogIcons.ttf
